version: "3"
services:
  api:
    image: node:17-slim
    container_name: SERVICECLIENTES
    build: .
    ports:
      - 3000:3000
    volumes:
      - api:/api
    working_dir: /api
    networks:
      - host

volumes:
  api:

networks:
  host:
    driver: bridge
