version: "3"
services:
  api2:
    image: node:17-slim
    container_name: SERVICEFINANCIAL
    build: .
    ports:
      - 4000:4000
    volumes:
      - api2:/api2
    working_dir: /api2
    networks:
      - host

volumes:
  api2:

networks:
  host:
    driver: bridge
